import type { Path } from "./types";

export const learningPaths: Path[] = [
    {
        id: 1,
        chapter: "Chapter I",
        title: "The World of Money",
        subtitle: "Begin Your Adventure",
        description:
            "Discover why money exists, how it evolved, and why sound money matters.",
        image: "/assets/images/path-book.png",
        duration: "20 min",
        lessons: 6,
        difficulty: "Beginner",
        reward: "+100 XP",
        progress: 100,
        status: "completed",
        color: "from-pink-500 to-orange-400",
        href: "/learn/money",
    },
    {
        id: 2,
        chapter: "Chapter II",
        title: "The Inflation Empire",
        subtitle: "Your First Boss",
        description:
            "Learn how inflation silently reduces purchasing power and changes the economy.",
        image: "/assets/images/path-inflation.png",
        duration: "25 min",
        lessons: 8,
        difficulty: "Easy",
        reward: "+150 XP",
        progress: 60,
        status: "current",
        color: "from-orange-500 to-yellow-400",
        href: "/learn/inflation",
    },
    {
        id: 3,
        chapter: "Chapter III",
        title: "Bitcoin Revolution",
        subtitle: "The New Hope",
        description:
            "Understand why Bitcoin was created and how it solves the problems of fiat money.",
        image: "/assets/images/aiGold.png",
        duration: "35 min",
        lessons: 10,
        difficulty: "Intermediate",
        reward: "+250 XP",
        progress: 0,
        status: "locked",
        color: "from-yellow-400 to-orange-500",
        href: "/learn/bitcoin",
    },
    {
        id: 4,
        chapter: "Chapter IV",
        title: "Proof of Work",
        subtitle: "Mining Kingdom",
        description:
            "Explore mining, energy, and why Proof of Work protects the Bitcoin network.",
        image: "/assets/images/work.png",
        duration: "30 min",
        lessons: 8,
        difficulty: "Intermediate",
        reward: "+300 XP",
        progress: 0,
        status: "locked",
        color: "from-purple-500 to-pink-500",
        href: "/learn/proof-of-work",
    },
    {
        id: 5,
        chapter: "Chapter V",
        title: "Self Custody",
        subtitle: "Protect Your Treasure",
        description:
            "Master hardware wallets, seed phrases, and long-term Bitcoin security.",
        image: "/assets/images/path-security.png",
        duration: "40 min",
        lessons: 12,
        difficulty: "Advanced",
        reward: "+500 XP",
        progress: 0,
        status: "locked",
        color: "from-cyan-500 to-blue-500",
        href: "/learn/security",
    },
];